trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  organization: modellingmind

jobs:
- job: DockerLogin
  displayName: 'Login to docker hub with service user'
  steps:
  - script: docker login -u $(DOCKERHUBUSER) --password $(DOCKERHUBTOKEN)

- job: CUDA10
  dependsOn: DockerLogin
  displayName: 'Build and publish Ubuntu 18.04 CUDA 10.0 CUDNN 7 containers'
  variables:
    ubuntu: ubuntu18.04
    cuda: 10.0
    cudnn: cudnn7
    base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
    tag: $(ubuntu)-$(cuda)-$(cudnn)
  steps:
  - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Build cuda opengl docker"
  - script: user-layer/build.sh $(organization)/cuda-cudnn-opengl:$(tag) cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Build user layer docker"
  - script: steam-games/build.sh $(organization)/cuda-cudnn-opengl-userlayer:$(tag) cuda-steam-gaming:$(tag)
    displayName: "Build steam docker"

  - script: docker push $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Push cuda opengl docker"
  - script: docker push $(organization)/cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Push cuda userlayer docker"
  - script: docker push $(organization)/cuda-steam-docker:$(tag)
    displayName: "Push cuda steam docker"

- job: CUDA101
  dependsOn: DockerLogin
  displayName: 'Build and publish Ubuntu 18.04 CUDA 10.1 CUDNN 7 containers'
  variables:
    ubuntu: ubuntu18.04
    cuda: 10.1
    cudnn: cudnn7
    base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
    tag: $(ubuntu)-$(cuda)-$(cudnn)
  steps:
  - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Build cuda opengl docker"
  - script: user-layer/build.sh $(organization)/cuda-cudnn-opengl:$(tag) cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Build user layer docker"
  - script: steam-games/build.sh $(organization)/cuda-cudnn-opengl-userlayer:$(tag) cuda-steam-gaming:$(tag)
    displayName: "Build steam docker"

  - script: docker push $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Push cuda opengl docker"
  - script: docker push $(organization)/cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Push cuda userlayer docker"
  - script: docker push $(organization)/cuda-steam-docker:$(tag)
    displayName: "Push cuda steam docker"

- job: CUDA102
  dependsOn: DockerLogin
  displayName: 'Build and publish Ubuntu 18.04 CUDA 10.1 CUDNN 7 containers'
  variables:
    ubuntu: ubuntu18.04
    cuda: 10.1
    cudnn: cudnn7
    base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
    tag: $(ubuntu)-$(cuda)-$(cudnn)
  steps:
  - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Build cuda opengl docker"
  - script: user-layer/build.sh $(organization)/cuda-cudnn-opengl:$(tag) cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Build user layer docker"
  - script: steam-games/build.sh $(organization)/cuda-cudnn-opengl-userlayer:$(tag) cuda-steam-gaming:$(tag)
    displayName: "Build steam docker"

  - script: docker push $(organization)/cuda-cudnn-opengl:$(tag)
    displayName: "Push cuda opengl docker"
  - script: docker push $(organization)/cuda-cudnn-opengl-userlayer:$(tag)
    displayName: "Push cuda userlayer docker"
  - script: docker push $(organization)/cuda-steam-docker:$(tag)
    displayName: "Push cuda steam docker"

  - script: |
      docker tag $(organization)/cuda-cudnn-opengl:$(tag) $(organization)/cuda-cudnn-opengl:latest
      docker tag $(organization)/cuda-cudnn-opengl-userlayer:$(tag) $(organization)/cuda-cudnn-opengl-userlayer:latest
      docker tag $(organization)/cuda-steam-docker:$(tag) $(organization)/cuda-steam-docker:latest
    displayName: "Mark CUDA 10.2 images as latest"
  - script: |
      docker push $(organization)/cuda-cudnn-opengl:latest
      docker push $(organization)/cuda-cudnn-opengl-userlayer:latest
      docker push $(organization)/cuda-steam-docker:latest
    displayName: "Push latest tags for all images"
