trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker login -u $DOCKERHUBUSER --password $DOCKERHUBTOKEN 
    # these variables are stored secretly in the Azure pipeline
  displayName: 'Login to docker hub with service user'

- script: |
    ./build_all.sh
  displayName: 'Build all containers'
