trigger:
  - master
pr:
  branches:
    include:
      - master
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: secrets
  - name: dockerhub_org
    value: xmindai
  - name: ubuntu
    value: ubuntu18.04
  - name: azure_dtr
    value: xmind.azurecr.io

stages:
  - stage: DockerDependencyTest
    displayName: "Login to docker hub with service user"
    jobs:
      - job: TestLoginDockerHub
        steps:
          - checkout: none
          - script: echo "$(dockerhub-token)" | docker login -u $(dockerhub-user) --password-stdin
      - job: TestLoginAzureRegistry
        steps:
          - checkout: none
          - script: echo "$(azure-container-registry-password)" | docker login -u $(azure-container-registry-user) --password-stdin $(azure_dtr)
  - stage: Build_CUDA_10
    dependsOn:
      - DockerDependencyTest
    jobs:
      - job: CUDA10
        timeoutInMinutes: 120
        displayName: "Build and publish Ubuntu 18.04 CUDA 10.0 CUDNN 7 containers"
        variables:
          cuda: 10.0
          cudnn: cudnn7
          base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
          tag: $(ubuntu)-$(cuda)-$(cudnn)
        steps:
          - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
            displayName: "Build cuda opengl docker"
          - script: cd ci && ./build_cuda_cpp.sh $(dockerhub_org)/cuda-cudnn-opengl:$(tag) $(dockerhub_org)/cuda-cpp:$(tag)
            displayName: "Build cuda-cpp docker"
          - script: cd ci && ./build_cuda_python.sh ubuntu:18.04 $(dockerhub_org)/cuda-python:$(tag) $(cuda)
            displayName: "Build cuda-python docker"

          - script: echo "$(dockerhub-token)" | docker login -u $(dockerhub-user) --password-stdin
            displayName: "Docker login"
          - script: |
              docker push $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
              docker push $(dockerhub_org)/cuda-cpp:$(tag)
              docker push $(dockerhub_org)/cuda-python:$(tag)
              docker system prune -a
            displayName: "Push all containers"
            condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  - stage: Build_CUDA_10_1
    dependsOn:
      - DockerDependencyTest
    jobs:
      - job: CUDA101
        timeoutInMinutes: 120
        displayName: "Build and publish Ubuntu 18.04 CUDA 10.1 CUDNN 7 containers"
        variables:
          cuda: 10.1
          cudnn: cudnn7
          base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
          tag: $(ubuntu)-$(cuda)-$(cudnn)
        steps:
          - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
            displayName: "Build cuda opengl docker"
          - script: cd ci && ./build_cuda_cpp.sh $(dockerhub_org)/cuda-cudnn-opengl:$(tag) $(dockerhub_org)/cuda-cpp:$(tag)
            displayName: "Build cuda-cpp docker"
          - script: cd ci && ./build_cuda_python.sh ubuntu:18.04 $(dockerhub_org)/cuda-python:$(tag) $(cuda)
            displayName: "Build cuda-python docker"

          - script: echo "$(dockerhub-token)" | docker login -u $(dockerhub-user) --password-stdin
            displayName: "Docker login"
          - script: |
              docker push $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
              docker push $(dockerhub_org)/cuda-cpp:$(tag)
              docker push $(dockerhub_org)/cuda-python:$(tag)
              # CUDA 10.1 is the last version supported by PyTorch, to be changed later
              docker tag  $(dockerhub_org)/cuda-python:$(tag) $(dockerhub_org)/cuda-python:latest
              docker push $(dockerhub_org)/cuda-python:latest
              docker system prune -a
            displayName: "Push all containers"
            condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  - stage: Build_CUDA_10_2
    dependsOn:
      - DockerDependencyTest
    jobs:
      - job: CUDA102
        timeoutInMinutes: 120
        displayName: "Build and publish Ubuntu 18.04 CUDA 10.2 CUDNN 7 containers"
        variables:
          cuda: 10.2
          cudnn: cudnn7
          base_tag: $(cuda)-$(cudnn)-devel-$(ubuntu)
          tag: $(ubuntu)-$(cuda)-$(cudnn)
        steps:
          - script: nvidia-cuda-cudnn-opengl/build.sh nvidia/cuda:$(base_tag) $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
            displayName: "Build cuda opengl docker"
          - script: cd ci && ./build_cuda_cpp.sh $(dockerhub_org)/cuda-cudnn-opengl:$(tag) $(dockerhub_org)/cuda-cpp:$(tag)
            displayName: "Build cuda-cpp docker"
          # Pytorch does not support cuda 10.2 now...
          # - script: cd ci && ./build_cuda_python.sh $(dockerhub_org)/cuda-cudnn-opengl:$(tag) $(dockerhub_org)/cuda-python:$(tag) $(cuda)
          #   displayName: "Build cuda-python docker"

          - script: echo "$(dockerhub-token)" | docker login -u $(dockerhub-user) --password-stdin
            displayName: "Docker login"
          - script: |
              docker push $(dockerhub_org)/cuda-cudnn-opengl:$(tag)
              docker push $(dockerhub_org)/cuda-cpp:$(tag)
              # docker push $(dockerhub_org)/cuda-python:$(tag)
              docker tag  $(dockerhub_org)/cuda-cudnn-opengl:$(tag)  $(dockerhub_org)/cuda-cudnn-opengl:latest
              docker push $(dockerhub_org)/cuda-cudnn-opengl:latest
              docker tag $(dockerhub_org)/cuda-cpp:$(tag) $(dockerhub_org)/cuda-cpp:latest
              docker push $(dockerhub_org)/cuda-cpp:latest
              docker system prune -a
            displayName: "Push all containers"
            condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  - stage: TestContainers
    dependsOn:
      - Build_CUDA_10
      - Build_CUDA_10_1
      - Build_CUDA_10_2
    jobs:
      - job: Unittest
        steps:
          - checkout: self
          - script: echo "please write tests for the containers..."

  - stage: PublishToAzure
    dependsOn:
      - TestContainers
    jobs:
      - job: Unittest
        steps:
          - checkout: self
          - script: echo "Internal publishing for faster deployment"
